O1MINIAPIKEY = "EK9jJWkyyVJjVVSt4B1qLPpC2c0siRAX2cZ2GGvnB7XydIEKaRIeJQQJ99BBACYeBjFXJ3w3AAABACOGjDp7"
O1MINIAPI_BASE = "https://gjboteastus.openai.azure.com/"
GPT4APIKEY = "BhnheqA2pJxY2fQGUZ4bSKVuObOyzxanjNlN4ofQ4WBi5UlLDX2NJQQJ99BAACmepeSXJ3w3AAABACOGUiWu"
GPT4API_BASE = "https://gjbot.openai.azure.com/"