AZURE_OPENAI_API_KEY = "BhnheqA2pJxY2fQGUZ4bSKVuObOyzxanjNlN4ofQ4WBi5UlLDX2NJQQJ99BAACmepeSXJ3w3AAABACOGUiWu"
AZURE_OPENAI_API_BASE = "https://gjbot.openai.azure.com/"
AZURE_OPENAI_DEPLOYMENT = "gpt-4"